### ISSUE TITLE
[Feature Request] Add Hover Effect To Generic Button

### ISSUE THREAD

**Issue by thekevinge** [UTDNebula/planner#346]
## Overview
Relies on #343, must get that done first.

Add hover effect to generic Button component. 

Caleb and I wanted something subtle like the buttons on this website: https://danielkorpai.com

Here's the CSS for it.
```css
.button:hover {
    box-shadow: inset 0 -1px 0 rgba(0,0,0,0.1), 0 2px 6px rgba(0,0,0,0.05), 0 7px 14px rgba(28,35,139,0.15);
    transform: translateY(-1px);
}
```

Let us know if you have concerns, and we can run it past design.
